server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: OWNjNmEwZTgwODA2YmM2N2VkYmMzMjZlNjUxN2I1Y2UxYzFmNDdkYTJmOGU1NmQ1YjQ1YTk1OGExNTk3Y2EzMWFhOTUxMjU0ZGE1MTBlODU0N2Y3NGUzODJkYWU5YjRjYTQ3OGM0MDFmMDcwYzlmODY2MjRhNTFmZTZkMTQ5OGQ=



springdoc:
  swagger-ui:
    enabled: true